import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Vehicle } from './vehicle.entity';
import { MaintenanceStatus } from './enums';

@Entity('maintenance_logs')
export class MaintenanceLog {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToOne(() => Vehicle, (vehicle) => vehicle.maintenanceLogs, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'vehicleId' })
  vehicle!: Vehicle;

  @Index()
  @Column({ type: 'uuid' })
  vehicleId!: string;

  @Column()
  description!: string;

  @Column({
    type: 'enum',
    enum: MaintenanceStatus,
    default: MaintenanceStatus.PENDING,
  })
  status!: MaintenanceStatus;

  @Column({ nullable: true })
  mechanicName!: string | null;

  @Column({ type: 'text', nullable: true })
  notes!: string | null;

  /** True when the entry was generated by the AI assistant/workflows */
  @Column({ default: false })
  recommendedByAi!: boolean;

  @Column({ type: 'timestamptz', nullable: true })
  performedAt!: Date | null;

  @CreateDateColumn()
  createdAt!: Date;
}
